title: Practice
subtitle: makes perfect
name: Toby Qin
# logo: "apple-touch-icon.png"
email:
description: >- # this means to ignore newlines until "baseurl:"
  This is another blog to share thoughts and experience in software testing and DevOps.

twitter_username: toby_qin
github_username: tobyqin
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /posts/:year-:month-:day/:title/
paginate: 10 # amount of posts to show
paginate_path: /page/:num/
timezone: Asia/Chongqing # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - _archive
  _ _drafts

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: 'Toby Qin'
  avatar: "/assets/images/avatar.jpg"
  # avatar: 'https://avatars1.githubusercontent.com/u/14037644'
  bio: 'Software Engineer in Testing and DevOps, Join me to be Cloud Native :-)'
  location: "Shanghai, China"
  links:
    - label: 'CnBlogs'
      icon: 'fas fa-fw fa-link'
      url: 'https://www.cnblogs.com/cicaday/'
    - label: 'GitHub'
      icon: 'fab fa-fw fa-github'
      url: 'https://github.com/tobyqin'
    - label: 'Twitter'
      icon: 'fab fa-fw fa-twitter-square'
      url: 'https://twitter.com/toby_qin'
    - label: 'LinkedIn'
      icon: 'fab fa-fw fa-linkedin'
      url: 'https://www.linkedin.com/in/toby-qin-2684a630/'

footer:
  links:
    - label: 'GitHub'
      icon: 'fab fa-fw fa-github'
      url: 'https://github.com/tobyqin'
    - label: 'Twitter'
      icon: 'fab fa-fw fa-twitter-square'
      url: 'https://twitter.com/toby_qin'
    - label: 'LinkedIn'
      icon: 'fab fa-fw fa-linkedin'
      url: 'https://www.linkedin.com/in/toby-qin-2684a630/'

defaults:
  # _posts
  - scope:
      path: ''
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
  # _pages
  - scope:
      path: '_pages'
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

comments:
  provider: "disqus"
  disqus:
    shortname: "https-betacat-online"